In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_csv("data/dataset.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55033 entries, 0 to 55032
Data columns (total 93 columns):
 #   Column                                                                                                          Non-Null Count  Dtype
---  ------                                                                                                          --------------  -----
 0   id_istat                                                                                                        55033 non-null  int64
 1   id_comune                                                                                                       55032 non-null  object
 2   cap                                                                                                             55033 non-null  int64
 3   Provincia                                                                                                       55033 non-null  object
 4   Regione                                                                                                         55033 non-null  object
 5   Ripartizione Geografica                                                                                         55033 non-null  object
 6   id_catastale                                                                                                    55033 non-null  object
 7   Latitudine                                                                                                      55033 non-null  float64
 8   Longitudine                                                                                                     55033 non-null  float64
 9   Superficie in km2                                                                                               55033 non-null  float64
 10  Indice di spopolamento                                                                                          55032 non-null  float64
 11  Codice regione                                                                                                  55033 non-null  int64
 12  Capoluogo_enc                                                                                                   55033 non-null  int64
 13  Reddito Pro-Capite per l'anno di riferimento                                                                    55033 non-null  float64
 14  Codice comuni                                                                                                   55033 non-null  float64
 15  Esercizi a 5 stelle                                                                                             55033 non-null  float64
 16  Letti                                                                                                           55033 non-null  float64
 17  Camere                                                                                                          55033 non-null  float64
 18  Bagni                                                                                                           55033 non-null  float64
 19  Esercizi a 4 stelle                                                                                             55033 non-null  float64
 20  Letti.1                                                                                                         55033 non-null  float64
 21  Camere.1                                                                                                        55033 non-null  float64
 22  Bagni.1                                                                                                         55033 non-null  float64
 23  Esercizi a 3 stelle                                                                                             55033 non-null  float64
 24  Letti.2                                                                                                         55033 non-null  float64
 25  Camere.2                                                                                                        55033 non-null  float64
 26  Bagni.2                                                                                                         55033 non-null  float64
 27  Esercizi a 2 stelle                                                                                             55033 non-null  float64
 28  Letti.3                                                                                                         55033 non-null  float64
 29  Camere.3                                                                                                        55033 non-null  float64
 30  Bagni.3                                                                                                         55033 non-null  float64
 31  Esercizi a 1 stella                                                                                             55033 non-null  float64
 32  Letti.4                                                                                                         55033 non-null  float64
 33  Camere.4                                                                                                        55033 non-null  float64
 34  Bagni.4                                                                                                         55033 non-null  float64
 35  Esercizi turistico-alberghiere                                                                                  55033 non-null  float64
 36  Letti.5                                                                                                         55033 non-null  float64
 37  Camere.5                                                                                                        55033 non-null  float64
 38  Bagni.5                                                                                                         55033 non-null  float64
 39  Esercizi alberghieri                                                                                            55033 non-null  float64
 40  Letti.6                                                                                                         55033 non-null  float64
 41  Camere.6                                                                                                        55033 non-null  float64
 42  Bagni.6                                                                                                         55033 non-null  float64
 43  Numero campeggi e villaggi turistici                                                                            55033 non-null  float64
 44  Letti.7                                                                                                         55033 non-null  float64
 45  Numero di alloggi in affitto gestiti in forma imprenditoriale                                                   55033 non-null  float64
 46  Letti.8                                                                                                         55033 non-null  float64
 47  Numero di agriturismi                                                                                           55033 non-null  float64
 48  Letti.9                                                                                                         55033 non-null  float64
 49  Numero di ostelli per la giovent√π                                                                               55033 non-null  float64
 50  Letti.10                                                                                                        55033 non-null  float64
 51  Numero di case per ferie                                                                                        55033 non-null  float64
 52  Letti.11                                                                                                        55033 non-null  float64
 53  Numero di rifugi alpini                                                                                         55033 non-null  float64
 54  Letti.12                                                                                                        55033 non-null  float64
 55  Numero di altri esercizi ricettivi                                                                              55033 non-null  float64
 56  Letti.13                                                                                                        55033 non-null  float64
 57  Numero di b&b                                                                                                   55033 non-null  float64
 58  Letti.14                                                                                                        55033 non-null  float64
 59  Numero di esercizi extra-alberghieri                                                                            55033 non-null  float64
 60  Letti.15                                                                                                        55033 non-null  float64
 61  Numero                                                                                                          55033 non-null  float64
 62  Letti.16                                                                                                        55033 non-null  float64
 63  Indice di occupazione                                                                                           55032 non-null  float64
 64  Indice disoccupazione                                                                                           55028 non-null  float64
 65  Reddito da fabbricati - Frequenza                                                                               55033 non-null  int64
 66  Reddito da lavoro dipendente e assimilati - Frequenza                                                           55033 non-null  int64
 67  Reddito da pensione - Frequenza                                                                                 55033 non-null  int64
 68  Reddito da lavoro autonomo (comprensivo dei valori nulli) - Frequenza                                           55033 non-null  float64
 69  Reddito di spettanza dell'imprenditore in contabilita' ordinaria  (comprensivo dei valori nulli) - Frequenza    55033 non-null  float64
 70  Reddito di spettanza dell'imprenditore in contabilita' semplificata (comprensivo dei valori nulli) - Frequenza  55033 non-null  float64
 71  Reddito complessivo minore o uguale a zero euro - Frequenza                                                     55033 non-null  float64
 72  Reddito complessivo da 0 a 10000 euro - Frequenza                                                               55033 non-null  int64
 73  Reddito complessivo da 10000 a 15000 euro - Frequenza                                                           55033 non-null  float64
 74  Reddito complessivo da 15000 a 26000 euro - Frequenza                                                           55033 non-null  int64
 75  Reddito complessivo da 26000 a 55000 euro - Frequenza                                                           55033 non-null  float64
 76  Reddito complessivo da 55000 a 75000 euro - Frequenza                                                           55033 non-null  float64
 77  Reddito complessivo da 75000 a 120000 euro - Frequenza                                                          55033 non-null  float64
 78  Reddito complessivo oltre 120000 euro - Frequenza                                                               55033 non-null  float64
 79  Fascia                                                                                                          55033 non-null  object
 80  Descrizione Zona                                                                                                55033 non-null  object
 81  Sottofascia Zona                                                                                                55033 non-null  object
 82  Descrizione Tipologia di Immobile                                                                               55033 non-null  object
 83  id_univoco                                                                                                      55033 non-null  object
 84  Costo Minimo alla Vendita                                                                                       55033 non-null  float64
 85  Costo Massimo alla Vendita                                                                                      55033 non-null  float64
 86  Media Costo alla Vendita                                                                                        55033 non-null  int64
 87  Costo Minimo alla Locazione                                                                                     55033 non-null  float64
 88  Costo Massimo alla Locazione                                                                                    55033 non-null  float64
 89  Media Costo alla Locazione                                                                                      55033 non-null  float64
 90  Circoscrizione Turistica                                                                                        54063 non-null  object
 91  Cod. Circoscrizione Turistica                                                                                   54063 non-null  float64
 92  Tipo di localit√†                                                                                                54063 non-null  object
dtypes: float64(71), int64(10), object(12)
memory usage: 39.0+ MB

# Calcoliamo la media costo alla vendita

In [12]:
# inserisci all'interno della colonna Media Costo alla Vendita la media delle colonne Costo Minimo alla Vendita e Costo Massimo alla Vendita
df["Media Costo alla Vendita"] = (df["Costo Minimo alla Vendita"] + df["Costo Massimo alla Vendita"]) / 2

In [13]:
df[df["Tipo di localit√†"].isnull()]

,id_istat,id_comune,cap,Provincia,Regione,Ripartizione Geografica,id_catastale,Latitudine,Longitudine,Superficie in km2,...,id_univoco,Costo Minimo alla Vendita,Costo Massimo alla Vendita,Media Costo alla Vendita,Costo Minimo alla Locazione,Costo Massimo alla Locazione,Media Costo alla Locazione,Circoscrizione Turistica,Cod. Circoscrizione Turistica,Tipo di localit√†
93,1049,Campiglione Fenile,10060,Torino,Piemonte,Nord-ovest,B512,44.802153,7.325070,11.3346,...,B512_B1_Abitazioni civili,620.0,930.0,775.0,2.5,3.7,3.10,NaN,NaN,NaN
167,1086,Ciri√®,10073,Torino,Piemonte,Nord-ovest,C722,45.231728,7.604588,17.5374,...,C722_B1_Abitazioni di tipo economico,700.0,1050.0,875.0,4.6,6.9,5.75,NaN,NaN,NaN
168,1086,Ciri√®,10073,Torino,Piemonte,Nord-ovest,C722,45.231728,7.604588,17.5374,...,C722_C1_Abitazioni civili,970.0,1450.0,1210.0,4.0,6.0,5.00,NaN,NaN,NaN
169,1086,Ciri√®,10073,Torino,Piemonte,Nord-ovest,C722,45.231728,7.604588,17.5374,...,C722_C1_Abitazioni civili,1450.0,2200.0,1825.0,5.4,8.1,6.75,NaN,NaN,NaN
170,1086,Ciri√®,10073,Torino,Piemonte,Nord-ovest,C722,45.231728,7.604588,17.5374,...,C722_E1_Abitazioni civili,930.0,1400.0,1165.0,3.7,5.6,4.65,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54580,108034,Muggi√≤,20835,Monza e della Brianza,Lombardia,Nord-ovest,F797,45.593667,9.229605,5.4815,...,F797_B1_Abitazioni civili,1350.0,1800.0,1575.0,4.8,6.9,5.85,NaN,NaN,NaN
54581,108034,Muggi√≤,20835,Monza e della Brianza,Lombardia,Nord-ovest,F797,45.593667,9.229605,5.4815,...,F797_D1_Abitazioni civili,1800.0,2450.0,2125.0,6.8,9.5,8.15,NaN,NaN,NaN
54582,108034,Muggi√≤,20835,Monza e della Brianza,Lombardia,Nord-ovest,F797,45.593667,9.229605,5.4815,...,F797_D1_Abitazioni civili,1350.0,1750.0,1550.0,5.0,6.7,5.85,NaN,NaN,NaN
54976,111064,San Nicol√≤ Gerrei,9040,Sud Sardegna,Sardegna,Isole,G383,39.495646,9.301434,63.8060,...,G383_B1_Abitazioni civili,500.0,600.0,550.0,1.7,2.0,1.85,NaN,NaN,NaN
54992,111075,Senorb√¨,9040,Sud Sardegna,Sardegna,Isole,I615,39.533008,9.132163,34.6867,...,I615_B2_Abitazioni civili,800.0,1100.0,950.0,3.2,4.3,3.75,NaN,NaN,NaN

In [25]:
df.columns

Index(['id_istat', 'id_comune', 'cap', 'Provincia', 'Regione',
       'Ripartizione Geografica', 'id_catastale', 'Latitudine', 'Longitudine',
       'Superficie in km2', 'Indice di spopolamento', 'Codice regione',
       'Capoluogo_enc', 'Reddito Pro-Capite per l'anno di riferimento',
       'Codice comuni', 'Esercizi a 5 stelle', 'Letti', 'Camere', 'Bagni',
       'Esercizi a 4 stelle', 'Letti.1', 'Camere.1', 'Bagni.1',
       'Esercizi a 3 stelle', 'Letti.2', 'Camere.2', 'Bagni.2',
       'Esercizi a 2 stelle', 'Letti.3', 'Camere.3', 'Bagni.3',
       'Esercizi a 1 stella', 'Letti.4', 'Camere.4', 'Bagni.4',
       'Esercizi turistico-alberghiere', 'Letti.5', 'Camere.5', 'Bagni.5',
       'Esercizi alberghieri', 'Letti.6', 'Camere.6', 'Bagni.6',
       'Numero campeggi e villaggi turistici', 'Letti.7',
       'Numero di alloggi in affitto gestiti in forma imprenditoriale',
       'Letti.8', 'Numero di agriturismi', 'Letti.9',
       'Numero di ostelli per la giovent√π', 'Letti.10',
       'Numero di case per ferie', 'Letti.11', 'Numero di rifugi alpini',
       'Letti.12', 'Numero di altri esercizi ricettivi', 'Letti.13',
       'Numero di b&b', 'Letti.14', 'Numero di esercizi extra-alberghieri',
       'Letti.15', 'Numero', 'Letti.16', 'Indice di occupazione',
       'Indice disoccupazione', 'Reddito da fabbricati - Frequenza',
       'Reddito da lavoro dipendente e assimilati - Frequenza',
       'Reddito da pensione - Frequenza',
       'Reddito da lavoro autonomo (comprensivo dei valori nulli) - Frequenza',
       'Reddito di spettanza dell'imprenditore in contabilita' ordinaria  (comprensivo dei valori nulli) - Frequenza',
       'Reddito di spettanza dell'imprenditore in contabilita' semplificata (comprensivo dei valori nulli) - Frequenza',
       'Reddito complessivo minore o uguale a zero euro - Frequenza',
       'Reddito complessivo da 0 a 10000 euro - Frequenza',
       'Reddito complessivo da 10000 a 15000 euro - Frequenza',
       'Reddito complessivo da 15000 a 26000 euro - Frequenza',
       'Reddito complessivo da 26000 a 55000 euro - Frequenza',
       'Reddito complessivo da 55000 a 75000 euro - Frequenza',
       'Reddito complessivo da 75000 a 120000 euro - Frequenza',
       'Reddito complessivo oltre 120000 euro - Frequenza', 'Fascia',
       'Descrizione Zona', 'Sottofascia Zona',
       'Descrizione Tipologia di Immobile', 'id_univoco',
       'Costo Minimo alla Vendita', 'Costo Massimo alla Vendita',
       'Media Costo alla Vendita', 'Costo Minimo alla Locazione',
       'Costo Massimo alla Locazione', 'Media Costo alla Locazione',
       'Circoscrizione Turistica', 'Cod. Circoscrizione Turistica',
       'Tipo di localit√†'],
      dtype='object')

In [8]:
df[df["Tipo di localit√†"].isnull()]["Provincia"].value_counts()

Provincia
Trento       228
Vicenza       42
Como          30
Belluno       29
Torino        28
            ...
Lodi           2
Pordenone      2
Rovigo         1
Trapani        1
Isernia        1
Name: count, Length: 74, dtype: int64

In [21]:
# Mostrare il nome del comune di Isernia con nan in tipo di localit√†
df[df["Provincia"] == "Trento"]["id_comune"][df["Tipo di localit√†"].isnull()]

15380    Baselga di Pin√®
15381    Baselga di Pin√®
15382    Baselga di Pin√®
15383    Baselga di Pin√®
15384    Baselga di Pin√®
              ...
16362    Ville di Fiemme
16363    Ville di Fiemme
16364    Ville di Fiemme
16365    Ville di Fiemme
16366    Ville di Fiemme
Name: id_comune, Length: 228, dtype: object